name: WP Readme 
description: Change README.md to readme.txt in WordPress style.

runs:
  using: "composite"
  steps:
    - name: Check file existence.
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "README.md, readme.md"

    - name: Generate readme.txt
      if: steps.check_files.outputs.files_exists == 'true'
      shell: bash
      run: curl -L https://raw.githubusercontent.com/fumikito/wp-readme/master/wp-readme.php | php

