name: Versioning
description: Change version string in readme, plugin file, or style.css.
inputs:
  version:
    description: 'Version string. In many cases, github.ref'
    required: true
  files:
    description: 'Files to convert in CSV format. e.g. style.css, readme.txt'
    required: true
  prefix:
    description: 'Prefix to remove'
    required: false
    default: 'refs/tags/'

runs:
  using: "composite"
  steps:
    - name: Check file existence.
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: ${{ inputs.files }}

    - name: Change version and remove .bak
      if: steps.check_files.outputs.files_exists == 'true'
      shell: bash
      run: |
        # Set variables.
        PREFIX="${{ inputs.prefix }}"
        VERSION_STR="${{ inputs.version }}"
        VERSION=${VERSION_STR#"$PREFIX"}
        FILES="${{ inputs.files }}"
        for file in ${FILES//,/ }
        do
          # call your procedure/other scripts here below
          sed -i.bak "s/\(Version\|Stable Tag\)\(:[[:space:]]*\).*$/\1\2{$VERSION}/i" $file
          cat $file
          EXISTS=$(cat $file | grep $VERSION)
          if [ -z "$EXISTS" ]; then
              echo "Version string not found in $file"
              exit 1
          fi
          echo "{$file} is updated to {$VERSION}."
        done


