name: Backlog 
description: Send notification to Backlog if commit message includes issue number.
inputs:
  project:
    description: 'Project ID of backlog. e.g. PJ_STANDARD'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Send Notification to Backlog
      uses: bicstone/backlog-notify@master
      env:
        PROJECT_KEY: ${{ inputs.project }}
        API_HOST: tarosky.backlog.jp
        API_KEY: ${{ secrets.BACKLOG_API_KEY }}
