name: Workflow and Actions CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Yaml Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check Yaml Syntax
        run: |
          npm ci --ignore-scripts
          npm test

  phplint:
    uses: ./.github/workflows/phplint.yml
    with:
      working_directory: tests/sub

  php-shor-open-tag:
    uses: ./.github/workflows/php-short-open-tag.yml

  readme:
    name: Generate readme.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/wp-readme

      - name: Check file existence.
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "readme.txt"

      - name: Generate readme.txt
        if: steps.check_files.outputs.files_exists != 'true'
        shell: bash
        run: exit 1

  versioning:
    name: Version really changed?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/versioning
        with:
          version: "prefix/tag/99.99.99"
          files: "tests/plugin-main.php,tests/style.css"
          prefix: "prefix/tag/"

  tag-in-branch:
    name: "Check if this commit is in allowed branch"
    uses: ./.github/workflows/check-tag-in-branch.yml
    if: contains(github.ref, 'refs/tags/')
    with:
      allowed_branch: "main"

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [ readme, lint, versioning, phplint, php-shor-open-tag ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
