name: Workflow and Actions CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
 
jobs:
  lint:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check Yaml Syntax
        run: |
          npm install
          npm test
