name: Workflow and Actions CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Yaml Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check Yaml Syntax
        run: |
          npm install
          npm test

  phplint:
    uses: tarosky/workflows/.github/workflows/phplint.yml@feature/php-syntax-check

  readme:
    name: Generate readme.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: tarosky/workflows/actions/wp-readme@main

      - name: Check file existence.
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "readme.txt"

      - name: Generate readme.txt
        if: steps.check_files.outputs.files_exists != 'true'
        shell: bash
        run: exit 1

  versioning:
    name: Version really changed?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: tarosky/workflows/actions/versioning@main
        with:
          version: "prefix/tag/99.99.99"
          files: "tests/plugin-main.php,tests/style.css"
          prefix: "prefix/tag/"

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [ readme, lint, versioning, phpcs ]
    steps:
      - name: Display Status
        run: echo "OK"
