name: NPM syntax check CI

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node version to run test. If empty, reads .node-version file.'
        default: ''
        required: false
        type: string
      command:
        description: 'Command in package.json to run syntax check. Default "lint"'
        default: lint
        required: false
        type: string
      package:
        description: 'Command in package.json to build files. Default "" and not executed if empty.'
        default: ''
        required: false
        type: string
      working_directory:
        description: 'Working directory where package.json is located'
        default: '.'
        required: false
        type: string

jobs:
  npm-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version || '' }}
          node-version-file: ${{ inputs.node_version && '' || '.node-version' }}

      - name: Install NPM Packages
        run:  npm ci --ignore-scripts

      - name: Run Syntax Check
        run:  npm run ${{ inputs.command }}

      - name: Check build script to check if compilation success
        if:   ${{ inputs.package != '' }}
        run:  "npm run ${{ inputs.package }}"
