name: PHP Syntax Check

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to run php lint'
        default: "."
        required: false
        type: string
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to run php lint'
        default: "."
        required: false
        type: string

jobs:
  phplint:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            php: [7.4, 8.0, 8.1]
    steps:
      - uses: actions/checkout@main

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP lint
        run: |
          find ${{ inputs.path }} -name "*.php" -exec php -l {} \; | grep -v "No syntax errors" > output.txt
          if [ ! -s output.txt ]; then
            echo "No syntax error"
            exit 0
          else
            cat output.txt >&2
            exit 1
          fi
