name: PHP Syntax Check

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to run php lint'
        default: "."
        required: false
        type: string
      php_versions:
        description: 'JSON compatible list of PHP versions (e.g. ["7.4","8.0","8.1"])'
        required: false
        default: '["7.4","8.0","8.1"]'
        type: string
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to run php lint'
        default: "."
        required: false
        type: string
      php_versions:
        description: 'JSON compatible list of PHP versions (e.g. ["7.4","8.0","8.1"])'
        default: '["7.4","8.0","8.1"]'
        required: false
        type: string

jobs:
  phplint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ${{ fromJSON(inputs.php_versions) }}
    steps:
      - uses: actions/checkout@main

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install composer if exists
        if: ${{ hashFiles('./composer.json') != '' }}
        run: composer install --no-dev

      - name: Run PHP lint and save as file.
        run: |
          find ${{ inputs.path }} -name "*.php" -exec php -l {} \; > output.txt

      - name: Remove no syntax error file
        run: |
          sed -i '/^No syntax errors/d' output.txt
          cat output.txt
          php -r 'echo filesize( "output.txt" ) . "Byte:\t"; if ( 1 >= filesize( "output.txt" ) ) { echo "No error detected."; unlink( "output.txt" ); }'

      - name: Check if lint error exists
        if: ${{ hashFiles('output.txt') != '' }}
        shell: bash
        run: exit 1
